### ISSUE TITLE
Crash after read bin-file from ipa

### ISSUE THREAD

**Issue by ablazhey** [woodruffw/ruby-macho#1]
Hi. I read bin file from IPA bild 
MachO::MachOFile.new("/path/to/Payload/BuildTest.app/BuildTest")
and don't initialize, having exeption -
"MachO::FatBinaryError: Fat binaries must be loaded with MachO::FatFile"
I'm using Ubuntu 14 and ruby 1.9.3/2.2.1

**Comment by woodruffw** [comment]
Hi @ablazhey,

I assumed you closed it because you solved your problem - "fat" binaries currently have to be opened with `MachO::FatFile` and not `MachO::MachOFile`. This is a design deficiency, and I'll be fixing it soon.
