### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by UniqMartin** [woodruffw/ruby-macho#4]
Since you are cutting releases with actual version numbers as can be seen on [rubygems.org](https://rubygems.org/gems/ruby-macho/versions), I think it would be good to have that reflected in this repository. How do you feel about retroactively tagging previous releases and making that also a habit for future releases?

**Comment by woodruffw** [comment]
Definitely a good idea. I'll begin tagging now :+1:

**Comment by UniqMartin** [comment]
Awesome! :+1:
